version: '3.8'

services:
  app-blue:
    build: .
    container_name: yeope-app-blue
    restart: always
    init: true
    # ports: - "3000:3000" (Internal only)
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=yeope-redis
      - REDIS_PORT=6379
      - DB_USER=yeope_user
      - DB_NAME=yeope
      - DB_PASSWORD=yeope_password_2024
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - postgres
      - redis
    command: node src/index.js
    volumes:
      - ./uploads:/usr/src/app/public/uploads
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
    networks:
      - yeope-network

  app-green:
    build: .
    container_name: yeope-app-green
    restart: always
    init: true
    # ports: - "3000:3000" (Internal only)
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=yeope-redis
      - REDIS_PORT=6379
      - DB_USER=yeope_user
      - DB_NAME=yeope
      - DB_PASSWORD=yeope_password_2024
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - postgres
      - redis
    command: node src/index.js
    volumes:
      - ./uploads:/usr/src/app/public/uploads
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
    networks:
      - yeope-network

  nginx:
    image: nginx:stable-alpine
    container_name: yeope-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app-blue
      - app-green
    networks:
      - yeope-network

  postgres:
    image: postgres:13
    container_name: yeope-postgres
    environment:
      POSTGRES_DB: yeope
      POSTGRES_USER: yeope_user
      POSTGRES_PASSWORD: yeope_password_2024
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yeope_user -d yeope" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - yeope-network

  redis:
    image: redis:7-alpine
    container_name: yeope-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - yeope-network

volumes:
  postgres_data:
  redis_data:


networks:
  yeope-network:
    driver: bridge
